### ISSUE TITLE
Investigate python test failure

### ISSUE THREAD

**Issue by mbrobbel** [mbrobbel/dqcsim#100]
The Azure Pipelines Python 3.7 Linux [build](https://dev.azure.com/mbrobbel/dqcsim/_build/results?buildId=132) failed for master: https://github.com/mbrobbel/dqcsim/commit/38b96d3f4ccaffe351c5794ce215b17b3fa9c5c4 with:

```
======================================================================
FAIL: test_null_operator (dqcsim.tests.test_allocate_free.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vsts/work/1/s/python/dqcsim/tests/test_allocate_free.py", line 137, in test_null_operator
    {'cmd': 'free', 'qubits': {1:1, 2:2}},
AssertionError: Lists differ: [] != [{'cmd': 'allocate', 'qubits': {1: 1, 2: 2[51 chars] 2}}]

Second list contains 2 additional elements.
First extra element 0:
{'cmd': 'allocate', 'qubits': {1: 1, 2: 2}, 'cmds': []}

- []
+ [{'cmd': 'allocate', 'cmds': [], 'qubits': {1: 1, 2: 2}},
+  {'cmd': 'free', 'qubits': {1: 1, 2: 2}}]
```

Manual restart of pipeline for this commit [passed](https://dev.azure.com/mbrobbel/dqcsim/_build/results?buildId=133). We have to figure out if this is non-deterministic behaviour of the build, test or dqcsim.

**Comment by jvanstraten** [comment]
I think I've figured out where the problem lies. This test does the following:

 - instruct the frontend to call allocate through a host arb
 - instruct the frontend to call free through a host arb
 - instruct the backend to send us a call log for the above through a host arb

Also important is that there's an operator in between.

In all three cases above, the `ArbResponse` is not returned to the host until the downstream plugin acknowledges all gatestream requests made by the user's implementation, so without the operator this would for sure never happen (unless there's some very obscure problem remaining). However, operators would only postpone acknowledging the upstream request if postponed measurements were involved, versus *any* kind of asynchronous gatestream request. The reasoning was that only measurements should be observable. However, this test case is a clear counterexample. Therefore, *all* downstream requests forwarded by operators must be acknowledged before the operator forwards the acknowledgement.
