### ISSUE TITLE
Rename Gate to Operation

### ISSUE THREAD

**Issue by mbrobbel** [mbrobbel/dqcsim#339]
There are more valid use cases for what we currently call custom gates. These uses cases are conceptually different from quantum gates, and therefore I propose to rename `Gate` to `Operation`.

The example use case here is the `barrier` instruction in OpenQASM.

We should make up our minds before the initial release.

**Comment by jvanstraten** [comment]
I half-started refactoring today, but am not so sure about this change anymore now. It clicked in my head when I started refactoring gate stream to operation stream... realizing that it's called a gate stream because it contains only operations that operate on the quantum chip. The most classical operation that belongs here that I can think of is shuttle, which could also be written as a swap with some ArbData annotation. DQCsim's assumption is that all classical stuff has already been done before the first gatestream, and operation (to me) includes pure-classical operations.

I simply don't agree that `barrier` is within the scope of DQCsim's definition of a gate. I wouldn't even call it an operation; it only modifies the behavior of (re)schedulers and nothing else, like a pragma. I stand by my initial reasoning that it should be an ArbCmd if anything, to be ignored by any plugin that doesn't know about them. If you want to print a warning if a downstream plugin ignores it you can still do that by mandating a nonempty return value for the command, but I wouldn't bother. Following the original conceptual design for DQCsim, anything that would be affected by a barrier has no business being an operator or backend. At most it would be frontend-only if we're ever going to simulate some exotic classical pipeline that can do out-of-order execution. If we ever get to that point and want to split off the source file interpretation, we should add some pre-frontend thing, with some kind of generic instruction stream flowing between the pre-frontend and frontend, with instructions of the order of LLVM-IR, and a branch target stream flowing back. Basically modeling the instruction fetch interface in a generic way. A barrier instruction would make sense there, like like x86 has barrier-like instructions. But not in the gatestream.

The fact that QCA currently wants to abuse DQCsim's operators for compilation and optimization is exactly that: abuse. They are intended for purely quantum things such as error modeling, monitoring, and maybe things like optimizing simulation runtime by merging consecutive gates (after all error modeling has already been done, otherwise it would affect the results). If they want to use it for classical stuff within the capabilities of DQCsim that's fine and all, that's what arbs are for, but adding classical concepts to a fundamentally quantum-only thing in the DQCsim core would just be making a mess.

**Comment by mbrobbel** [comment]
I agree. Closing this issue.
